// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izsbncbdibkplutuqigt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6c2JuY2JkaWJrcGx1dHVxaWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODMyNjAsImV4cCI6MjA3MDE1OTI2MH0.VePKmS-SxixOO8fOU9UqvIOLCxltMTAQWgRkiuoQVzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});